config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks do
    member do
      post :toggle
    end
    get '/page/:page', action: :index, on: :collection
  end

  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :description, presence: true

  scope :search_by_description, ->(query) { where("description LIKE ?", "%#{query}%") }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  devise :database_authenticatable, :registerable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end

  def record_not_found
    flash[:alert] = 'Record not found'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :toggle, :update, :destroy]
  before_action :authorize_task, only: [:update, :toggle, :destroy]

  def index
    @tasks = current_user.tasks
    @tasks = @tasks.search_by_description(params[:query]) if params[:query].present?
    
    @tasks = @tasks.page(params[:page]).per(5)
    @task = Task.new
    authorize @tasks
  end

  def new
    @task = current_user.tasks.new
    authorize @task
  end

  def create
    @task = current_user.tasks.new(task_params)
    authorize @task
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @task.update(completed: params[:completed])
  
    render json: { message: "Success" }
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @task.destroy
      redirect_to tasks_url, notice: "Post was successfully deleted."
    else
      redirect_to tasks_url, notice: "Something went wrong"
    end
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def authorize_task
    authorize @task
  end

  def task_params
    params.require(:task).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="/" class="flex items-center">
        <img src="https://flowbite.com/docs/images/logo.svg" class="h-8 mr-3" alt="Flowbite Logo" />
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">TODO APP</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <% if current_user.present? %>
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800" %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800 w-48" %><br />
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'wind', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=render "layouts/navbar" %>
    <div id="flash-messages">
      <% flash.each do |key, value| %>
        <div class="alert <%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, class: "mb-7") do |form| %>
  <div class="mb-5">
    <%= form.text_field :description, placeholder: "Add new task", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
    <%= form.check_box :completed, class: 'hidden' %>
    <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<turbo-frame id="<%= dom_id task %>" class="block">
  <div class="block">
    <%= form_with(model: task, class:"text-lg inline-block my-3 w-72") do |form| %>
      <%= form.check_box :completed,
                        data: {
                          id: task.id,
                          action: "tasks#toggle"
                        },
                        class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500" %>
      <%= task.description %>
    <% end %>

    <%= link_to "Edit", edit_task_path(task),
                class: "btn bg-gray-100"
    %>
    <div class="inline-block ml-2">
      <%= button_to "Delete", task_path(task), method: :delete, data: { "turbo-frame": "_top" }, class: "btn bg-red-100" %>
    </div>
  </div>
</turbo-frame>

app/views/tasks/edit.html.erb
<div>
  <h1 class="font-bold text-2xl mb-3">Editing Task</h1>

  <turbo-frame id="<%= dom_id @task %>">
    <%= render "form", task: @task %>
    <%= link_to "Cancel", tasks_path, class: "btn mb-3 bg-gray-100" %>
  </turbo-frame>
</div>

app/views/tasks/index.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

<div class='px-5'>
  <h1 class="font-bold text-2xl">Task Manager</h1>
  <div class="mt-4 mx-auto flex flex-row justify-between">
    <div class="">
      <%= render "form", task: @task %>
    </div>
    <div class="">
      <%= form_with(url: tasks_path, method: "GET", id: "search-form") do |form| %>
        <%= form.text_field :query, id: "search-input", placeholder:"Search", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
        <%= form.submit 'Search', class: "btn py-2 ml-2 bg-green-600 text-white" %>
      <% end %>
    </div>
  </div>

  <div id="tasks">
    <h1 class="font-bold text-lg mb-7">Tasks</h1>
    <div class="" data-controller="tasks">
    <ul id="tasks-list" data-turbo-frame="tasks_list">
      <%= render @tasks %>
    </ul>
    </div>
  </div>
<div>
<div class='text-center p-7'>
  <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render 'form' %>